### ISSUE TITLE
require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by TomAFrench** [KingCosmic/random-id#6]
Hey, this module is being used in https://github.com/torusresearch/torus-embed which in turn I am using in a project.

The inclusion of this module is causing the warning:
```
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```
caused by how you are exporting the function; this is then causing CI to fail as it is set to fail on warnings.

Is the option to load the module globally through including it in a script tag necessary? As otherwise the if statement can be removed.

**Comment by KingCosmic** [comment]
Hey! sorry for the issue, yea I've been thinking of removing that if, but unsure who all is using it.

**Comment by KingCosmic** [comment]
I'll download your project in a moment and see if I can fix the issue where it doesnt error when i get the chance
